package com.example.electricianapp.data.model
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents a single task associated with a Job in the local Room database.
 * Maps directly to the 'tasks' table.
 */
@Entity(
    tableName = "tasks",
    // Defines a foreign key relationship between 'tasks' and 'jobs'.
    foreignKeys = [ForeignKey(
        entity = JobEntity::class,         // The parent table (JobEntity maps to 'jobs')
        parentColumns = ["id"],            // The primary key column in the parent table ('jobs')
        childColumns = ["jobId"],         // The foreign key column in this table ('tasks')
        onDelete = ForeignKey.CASCADE      // Rule: If a job is deleted, delete all its associated tasks.
    )],
    // Creates an index on the 'jobId' column for faster lookups of tasks belonging to a specific job.
    indices = [Index("jobId")]
)
data class TaskEntity(
    /** Local database primary key, auto-generated by Room. */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /** Foreign key referencing the 'id' column of the 'jobs' table. */
    var jobId: Long,

    /** Text description of what the task involves. */
    var description: String,

    /** Boolean flag indicating whether the task has been completed. Defaults to false. */
    var isCompleted: Boolean = false
)
