package com.example.electricalcalculator.data.db;

import android.content.Context;
import androidx.room.Database;
import androidx.room.Room;
import androidx.room.RoomDatabase;

import com.example.electricalcalculator.data.db.entity.ApplianceEntity;
import com.example.electricalcalculator.data.db.entity.BoxFillEntity;
import com.example.electricalcalculator.data.db.entity.BoxFillWireCrossRef;
import com.example.electricalcalculator.data.db.entity.DwellingUnitApplianceCrossRef;
import com.example.electricalcalculator.data.db.entity.DwellingUnitEntity;
import com.example.electricalcalculator.data.db.entity.WireEntity;

/**
 * Room database for the Electrician app
 */
@Database(entities = {
        BoxFillEntity.class,
        WireEntity.class,
        BoxFillWireCrossRef.class,
        DwellingUnitEntity.class,
        ApplianceEntity.class,
        DwellingUnitApplianceCrossRef.class
    }, version = 1, exportSchema = false)
public abstract class ElectricianDatabase extends RoomDatabase {
    // Database implementation will be generated by Room
    private static volatile ElectricianDatabase INSTANCE;

    public static ElectricianDatabase getInstance(Context context) {
        if (INSTANCE == null) {
            synchronized (ElectricianDatabase.class) {
                if (INSTANCE == null) {
                    INSTANCE = Room.databaseBuilder(
                            context.getApplicationContext(),
                            ElectricianDatabase.class,
                            "electrician_database")
                            .fallbackToDestructiveMigration()
                            .build();
                }
            }
        }
        return INSTANCE;
    }
}
